### ISSUE TITLE
cannot create an account

### ISSUE THREAD

**Issue by tpoonach** [AffiliateCoin/AffiliateCoin-Protocol#1]
![image](https://user-images.githubusercontent.com/36091419/36073563-d45c6264-0f00-11e8-81c3-07f377a5d13d.png)
does not like my email

**Comment by riccardoravaro** [comment]
We don't accept emails with protonmail domain for now, but we are working for resolve the issue, thank you for the feedback @tpoonach

**Comment by tpoonach** [comment]
Do you have an open source bounty program like utopian.io? I am thinking how to create a multi coin system that you could use.

**Comment by riccardoravaro** [comment]
No we haven't but it is we are going to have a look at it tomorrow, we are considering to open source part of the AffiliateCoin protocol and we need help for the translations.

**Comment by tpoonach** [comment]
Really we need a way to have people earn your coin while contributing instead of steem. The utopian.io is tied to steemit.com coin, but it is open source. I suppose you could make another bot that pays out in your coin for those contributions, another issue is then who will review the contributions. Really a different system is needed for other coins.
